branch-defaults:
  master:
    environment: HttpServer-env-1
environment-defaults:
  HttpServer-env-1:
    branch: master
    repository: HTTPServer
global:
  application_name: http_server
  default_ec2_keyname: null
  default_platform: Corretto 11 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
