version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:14.0.1-buster

    working_directory: ~/com.k3ntako.HTTPServer

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run: gradle test

  deploy:
    docker:
      - image: circleci/openjdk:14.0.1-buster

    working_directory: ~/com.k3ntako.HTTPServer
    steps:
      - checkout
      - run:
          name: Install python
          command: |
            sudo apt-get update
            sudo apt-get install software-properties-common
            sudo add-apt-repository --yes ppa:deadsnakes/ppa
            sudo apt-get install python3.7
            sudo apt-get install python3-pip
      - run:
          name: Install awsebcli
          command: sudo python3.7 -m pip install awsebcli --upgrade
      - run:
          name: Create AWS credentials
          command: |
            mkdir ~/.aws
            touch ~/.aws/config
            chmod 600 ~/.aws/config
            echo "[profile eb-user]" > ~/.aws/config
            echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> ~/.aws/config
            echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> ~/.aws/config
      - run:
          name: Create build jar
          command: ./gradlew build
      - run:
          name: Deploying
          command: eb deploy --profile eb-user --region us-east-1

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          filters:
            branches:
              only:
                - master
